paths:
  project: .
  data: data
  cines: data/cines
  hierarchical_data: data/hierarchical_data
  large_examples: data/large_examples
  large_sources: data/large_sources
  notes: data/notes
  profiles: data/profiles
  sheets: data/sheets
  uncompressed_contours: data/uncompressed_contours
  uncompressed_filled: data/uncompressed_filled
  uncompressed_sources: data/uncompressed_sources
  example_cines: data/example_cines
  large_example_cine: data/example_cines/2022-01-06T16-57-31.cine
  docx: data/docx
  html: data/html
  md: data/md
  media: data/media
  package: src/boilercv
  correlations: src/boilercv/correlations.py
  models: src/boilercv/models
  paths_module: src/boilercv/models/paths.py
  stages:
    compare_theory: src/boilercv/stages/compare_theory.py
    fill: src/boilercv/stages/fill.py
    find_contours: src/boilercv/stages/find_contours.py
    find_tracks: src/boilercv/stages/find_tracks.py
    find_unobstructed: src/boilercv/stages/find_unobstructed.py
    generate_reports: src/boilercv/stages/generate_reports.py
    preview_preview_binarized: src/boilercv/stages/preview/preview_binarized.py
    preview_preview_filled: src/boilercv/stages/preview/preview_filled.py
    preview_preview_gray: src/boilercv/stages/preview/preview_gray.py
  plot_config: data/plotting
  mpl_base: data/plotting/base.mplstyle
  mpl_hide_title: data/plotting/hide_title.mplstyle
  experiments: data/experiments
  notebooks: data/notebooks
  rois: data/rois
  samples: data/samples
  sources: data/sources
  contours: data/contours
  examples: data/examples
  filled: data/filled
  lifetimes: data/lifetimes
  tracks: data/tracks
  unobstructed: data/unobstructed
  previews: data/previews
  binarized_preview: data/previews/binarized.nc
  filled_preview: data/previews/filled.nc
  gray_preview: data/previews/gray.nc
