[florschuetz_chao_1965]
latex = '\beta = 1 - 4 \Ja \sqrt{\Fo_\o / \pi}'
sympy = 'Eq(beta, 1 - 4 * Ja * sqrt(Fo_0 / pi))'

[akiyama_1973]
latex = '\beta=(1 - 1.036 Re_\bo^{1/2} Pr^{1/3} Ja Fo_\o)^{0.714}'
sympy = 'Eq(beta, (1 - 1.036 * Re_b0**(1/2) * Pr**(1/3) * Ja * Fo_0)**0.714)'

[isenberg_sideman_1970]
latex = '''
\beta =
\left(1 - \left(3/\sqrt{\pi}\right) \Re_\bo^{1/2} \Pr^{1/3} Ja Fo_\o \right)^{2/3}
'''
sympy = 'Eq(beta, (1 - 3/sqrt(pi) * Re_b0**(1/2) * Pr**(1/3) * Ja * Fo_0)**(2/3))'

[yuan_et_al_2009]
latex = '''
\beta =
\left(
    1 - 1.8 \Re_\bo^{0.5} \Pr^{1/3} \Ja \Fo_\o \left(1 - 0.5 \Ja^{0.1} \Fo_\o\right)
\right)^{2/3}
'''
sympy = '''Eq(
beta, (1 - 1.8 * Re_b0**0.5 * Pr**(1/3) * Ja * Fo_0 * (1 - 0.5 * Ja**0.1 * Fo_0))**(2/3)
)'''
