[florschuetz_chao_1965.beta]
solutions = ["1 - 4*Ja*sqrt(Fo_0/pi)"]
warnings = []

[isenberg_sideman_1970.beta]
solutions = ["1 - 4*Ja*sqrt(Fo_0/pi)"]
warnings = []

[akiyama_1973.beta]
solutions = ["1 - 4*Ja*sqrt(Fo_0/pi)"]
warnings = []

[yuan_et_al_2009.beta]
solutions = ["1 - 4*Ja*sqrt(Fo_0/pi)"]
warnings = []
