[akiyama_1973]
[akiyama_1973.Fo_0]
solutions = []
warnings = []

[akiyama_1973.beta]
solutions = ["(1 - 1.036*Fo_0*Ja*Pr**(1/3)*Re_b0**(1/2))**0.714"]
warnings = []

[florschuetz_chao_1965]
[florschuetz_chao_1965.Fo_0]
solutions = []
warnings = [
    "could not verify solution {Fo_0: pi*(beta - 1)**2/(16*Ja**2)}.",
    "assumptions concerning following solution(s) cannot be checked: {Fo_0: pi*(beta - 1)**2/(16*Ja**2)}",
]

[florschuetz_chao_1965.beta]
solutions = ["1 - 4*Ja*sqrt(Fo_0/pi)"]
warnings = []

[isenberg_sideman_1970]
[isenberg_sideman_1970.Fo_0]
solutions = ["sqrt(pi)*(beta**(3/2) + 1)/(3*Ja*Pr**(1/3)*sqrt(Re_b0))"]
warnings = [
    "could not verify solution {Fo_0: sqrt(pi)*(beta**(3/2) + 1)/(3*Ja*Pr**(1/3)*sqrt(Re_b0))}.",
    "assumptions concerning following solution(s) cannot be checked: {Fo_0: sqrt(pi)*(beta**(3/2) + 1)/(3*Ja*Pr**(1/3)*sqrt(Re_b0))}, {Fo_0: sqrt(pi)*(1 - beta**(3/2))/(3*Ja*Pr**(1/3)*sqrt(Re_b0))}",
]

[isenberg_sideman_1970.beta]
solutions = ["(1 - 3*Fo_0*Ja*Pr**(1/3)*Re_b0**(1/2)/(sqrt(pi)))**(2/3)"]
warnings = []

[yuan_et_al_2009]
[yuan_et_al_2009.Fo_0]
solutions = [
    "1.0/Ja**(1/10) - 1.05409255338946*sqrt(0.9*Ja**2*Pr**0.333333333333333*Re_b0 - Ja**1.1*Re_b0**0.5*beta**1.5 - 1.0*Ja**1.1*Re_b0**0.5)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))",
    "1.0/Ja**(1/10) + 1.05409255338946*sqrt(0.9*Ja**2*Pr**0.333333333333333*Re_b0 - Ja**1.1*Re_b0**0.5*beta**1.5 - 1.0*Ja**1.1*Re_b0**0.5)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))",
    "1.0/Ja**(1/10) + 1.05409255338946*sqrt(0.9*Ja**2*Pr**0.333333333333333*Re_b0 + Ja**1.1*Re_b0**0.5*beta**1.5 - 1.0*Ja**1.1*Re_b0**0.5)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))",
]
warnings = [
    "could not verify solution {Fo_0: 1.0/Ja**(1/10) - 1.4142135623731*sqrt(1.0*_t**3*Ja**(11/10)*sqrt(Re_b0) - 0.555555555555556*Ja**(11/10)*sqrt(Re_b0) + 0.5*Ja**2*Pr**(1/3)*Re_b0)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}.",
    "could not verify solution {Fo_0: 1.0/Ja**(1/10) + 1.4142135623731*sqrt(1.0*_t**3*Ja**(11/10)*sqrt(Re_b0) - 0.555555555555556*Ja**(11/10)*sqrt(Re_b0) + 0.5*Ja**2*Pr**(1/3)*Re_b0)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}.",
    "could not verify solution {Fo_0: 1.0/Ja**(1/10) - 1.05409255338946*sqrt(-Ja**(11/10)*sqrt(Re_b0)*beta**(3/2) - 1.0*Ja**(11/10)*sqrt(Re_b0) + 0.9*Ja**2*Pr**(1/3)*Re_b0)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}.",
    "could not verify solution {Fo_0: 1.0/Ja**(1/10) - 1.05409255338946*sqrt(Ja**(11/10)*sqrt(Re_b0)*beta**(3/2) - 1.0*Ja**(11/10)*sqrt(Re_b0) + 0.9*Ja**2*Pr**(1/3)*Re_b0)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}.",
    "could not verify solution {Fo_0: 1.0/Ja**(1/10) + 1.05409255338946*sqrt(-Ja**(11/10)*sqrt(Re_b0)*beta**(3/2) - 1.0*Ja**(11/10)*sqrt(Re_b0) + 0.9*Ja**2*Pr**(1/3)*Re_b0)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}.",
    "could not verify solution {Fo_0: 1.0/Ja**(1/10) + 1.05409255338946*sqrt(Ja**(11/10)*sqrt(Re_b0)*beta**(3/2) - 1.0*Ja**(11/10)*sqrt(Re_b0) + 0.9*Ja**2*Pr**(1/3)*Re_b0)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}.",
    "assumptions concerning following solution(s) cannot be checked: {Fo_0: 1.0/Ja**(1/10) - 1.05409255338946*sqrt(0.9*Ja**2*Pr**0.333333333333333*Re_b0 - Ja**1.1*Re_b0**0.5*beta**1.5 - 1.0*Ja**1.1*Re_b0**0.5)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}, {Fo_0: 1.0/Ja**(1/10) - 1.05409255338946*sqrt(0.9*Ja**2*Pr**0.333333333333333*Re_b0 + Ja**1.1*Re_b0**0.5*beta**1.5 - 1.0*Ja**1.1*Re_b0**0.5)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}, {Fo_0: 1.0/Ja**(1/10) + 1.05409255338946*sqrt(0.9*Ja**2*Pr**0.333333333333333*Re_b0 - Ja**1.1*Re_b0**0.5*beta**1.5 - 1.0*Ja**1.1*Re_b0**0.5)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}, {Fo_0: 1.0/Ja**(1/10) + 1.05409255338946*sqrt(0.9*Ja**2*Pr**0.333333333333333*Re_b0 + Ja**1.1*Re_b0**0.5*beta**1.5 - 1.0*Ja**1.1*Re_b0**0.5)/(Ja**(11/10)*Pr**(1/6)*sqrt(Re_b0))}",
]

[yuan_et_al_2009.beta]
solutions = ["(1 - 1.8*Fo_0*Ja*Pr**(1/3)*Re_b0**0.5*(1 - 0.5*Fo_0*Ja**0.1))**(2/3)"]
warnings = []
