[florschuetz_chao_1965]
latex = ''
sympy = ''

[isenberg_sideman_1970]
latex = ''
sympy = ''

[akiyama_1973]
latex = ''
sympy = ''

[chen_mayinger_1992]
latex = ''
sympy = ''

[zeitoun_et_al_1995]
latex = ''
sympy = ''

[kalman_mori_2002]
latex = ''
sympy = ''

[warrier_et_al_2002]
latex = ''
sympy = ''

[yuan_et_al_2009]
latex = ''
sympy = ''

[lucic_mayinger_2010]
latex = ''
sympy = ''

[kim_park_2011]
latex = ''
sympy = ''

[al_issa_et_al_2014]
latex = ''
sympy = ''

[tang_et_al_2016]
latex = ''
sympy = ''
