[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "boilercv_tools"
version = "0.0.0"
description = "Tools."
dependencies = ["cyclopts==2.4.2"]

[tool.fawltydeps]
deps = ["pyproject.toml"]
code = ["."]
