# Lock dependencies if necessary, then test, lint, and update.comps
name: "ci"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**/pyproject.toml"
      - "requirements/**"
      - "scripts/Sync-Python.ps1"
      - "src/**"
      - "tests/**"
      - "tools/boilercv_tools.py"
      - "tools/boilercv_tools/**"
      - "submodules/**"
      - "codecov.yml"
      - "params.yaml"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ci.yml"
      - "**/pyproject.toml"
      - "requirements/**"
      - "scripts/Sync-Python.ps1"
      - "src/**"
      - "tests/**"
      - "tools/boilercv_tools.py"
      - "tools/boilercv_tools/**"
      - "submodules/**"
      - "codecov.yml"
      - "params.yaml"
jobs:
  ruff:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - shell: "pwsh"
        run: "scripts/Sync-Python.ps1"
      - run: "ruff --no-fix --output-format github ."
  fawltydeps:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - shell: "pwsh"
        run: "scripts/Sync-Python.ps1"
      - run: "fawltydeps"
  pyright:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - shell: "pwsh"
        run: "scripts/Sync-Python.ps1"
      - run: pyright
  test:
    strategy:
      matrix:
        github_actions_runner:
          - "macos-13"
          # - "macos-14" # ? PyTables doesn't support macos-14
          - "ubuntu-22.04"
          - "windows-2022"
        python_version:
          # - "3.10" # ? Using some 3.11 features (e.g. datetime.UTC)
          - "3.11"
          # - "3.12" # ? No support in my commit-pinned fork of cachier
    runs-on: "${{ matrix.github_actions_runner }}"
    steps:
      # ! https://askubuntu.com/questions/900285/libegl-so-1-is-not-a-symbolic-link
      - if: startsWith(matrix.github_actions_runner, 'ubuntu')
        name: "Install PySide6 system dependencies"
        run: "sudo apt update && sudo apt install libegl1"
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "${{ matrix.python_version }}"
      - shell: "pwsh"
        run: "scripts/Sync-Python.ps1 -Version '${{ matrix.python_version }}'"
      # ! https://github.com/pytest-dev/pytest-cov/issues/479#issuecomment-1247444988
      - run: "pytest --cov --cov-config pyproject.toml"
      - if: startsWith(matrix.github_actions_runner, 'ubuntu') && matrix.python_version == '3.11'
        uses: "codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab" # v4.1.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: smart-tests
          plugins: pycoverage,compress-pycoverage
      - uses: "actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3" # v4.3.1
        with:
          path: ".comps"
          name: "requirements_${{ matrix.github_actions_runner }}_${{ matrix.python_version }}"
  bump:
    if: github.event_name == 'pull_request'
    permissions:
      contents: "write"
    needs:
      - "ruff"
      - "fawltydeps"
      - "pyright"
      - "test"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          path: ".comps"
          merge-multiple: True
      - shell: "pwsh"
        run: "scripts/Sync-Python.ps1"
      - uses: "stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d" # v5.0.0
        with:
          commit_message: "Lock"
  lock:
    if: "${{ !(github.event_name == 'pull_request') }}"
    permissions:
      contents: "write"
    needs:
      - "ruff"
      - "fawltydeps"
      - "pyright"
      - "test"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - id: "changes"
        uses: "dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36" # v3.0.2
        with:
          filters: |
            deps:
              - "**/pyproject.toml"
              - "requirements/**"
              - "submodules/**"
      - if: steps.changes.outputs.deps == 'true'
        uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - if: steps.changes.outputs.deps == 'true'
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          path: ".comps"
          merge-multiple: True
      - if: steps.changes.outputs.deps == 'true'
        shell: "pwsh"
        run: "scripts/Sync-Python.ps1 -Lock"
      - if: steps.changes.outputs.deps == 'true'
        uses: "stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d" # v5.0.0
        with:
          commit_message: "Lock"
