# Simulate local dev run of `Sync-Python.ps1`
name: "contrib"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/contrib.yml"
      - "scripts/Initialize-Repo.ps1"
      - "tools/boilercv_tools.py"
      - "tools/boilercv_tools/**"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/contrib.yml"
      - "scripts/Initialize-Repo.ps1"
      - "tools/boilercv_tools.py"
      - "tools/boilercv_tools/**"
jobs:
  contrib:
    strategy:
      matrix:
        github_actions_runner:
          - "macos-13"
          - "ubuntu-22.04"
          - "windows-2022"
        venv_in_ci:
          - ""
          - "-VenvInCI"
    runs-on: "${{ matrix.github_actions_runner }}"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - shell: "pwsh"
        run: "scripts/Sync-Python.ps1 -Recompile -Lock -NoSync -NoCopy ${{ matrix.venv_in_ci }}"
