name: "docs"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]
    paths: ["**/pyproject.toml", "**/*.md", ".tools/**", "docs/**"]
permissions:
  contents: "read"
  pages: "write"
  id-token: "write"
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - shell: "pwsh"
        run: ".tools/scripts/Sync-Python.ps1"
      - run: "sphinx-build -EaT docs _site"
      - uses: "actions/upload-pages-artifact@v3.0.0"
  deploy:
    if: "${{ !(github.event_name == 'pull_request') }}"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-22.04"
    needs: "build"
    steps:
      - id: "deployment"
        uses: "actions/deploy-pages@v4.0.2"
