name: "minimum"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight.
jobs:
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
          latest-pins: false
      - name: Install PySide6 system dependencies
        run: |
          # https://askubuntu.com/questions/900285/libegl-so-1-is-not-a-symbolic-link
          sudo apt update
          sudo apt install libegl1
      - run: "pytest"
