name: "release"
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "dropseed/changerelease@v1.6.0"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: ""
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
          install-project: false
      - run: "flit publish"
        env:
          FLIT_USERNAME: "__token__"
          FLIT_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
