name: "test"
on: ["workflow_dispatch", "push"]
jobs:
  test:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - id: "changes"
        uses: "dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36" # v3.0.2
        with:
          list-files: "csv"
          filters: |
            deps:
              - "**/pyproject.toml"
              - "requirements/**"
